#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
echo -e "${GREEN}Examples:"
echo -e "feat: (new feature for the user, not a new feature for build script)"
echo -e "fix: (bug fix for the user, not a fix to a build script)"
echo -e "docs: (changes to the documentation)"
echo -e "style: (formatting, missing semi colons, etc; no production code change)"
echo -e "refactor: (refactoring production code, eg. renaming a variable)"
echo -e "test: (adding missing tests, refactoring tests; no production code change)"
echo -e "chore: (updating grunt tasks etc; no production code change)"
echo -e "revert: (reverting recent changes)"
echo -e "perf: (identify production changes)"
echo -e "ci: (identify development changes)"
echo -e "<type>[optional scope]: <description>"
echo -e "<type>[optional scope]: <description>"
COLOR_OFF='\033[0m'
echo -e "${COLOR_OFF}"
